### ISSUE TITLE
Add logging output

### ISSUE THREAD

**Issue by benhudson85** [cat-cfs/cbm3_python#12]
https://github.com/cat-cfs/cbm3_python/blob/f6cac6df40a662eb8d6a8dab65072865355cae06/cbm3_python/simulation/concurrent_runner.py#L125

Would it be possible to add some sort of console and/or logging output for the following?
- What simulations have been started, maybe using the input project database name or something similarly descriptive as a label?
- Simulation completion (with error recognition and elapsed time if possible) as it occurs?
- Newly started simulations and remain simulations in queue after each completed simulation?

**Comment by smorken** [comment]
this is possible, but needs to be addressed in calling applications
