### ISSUE TITLE
Add row to tblDisturbanceType

### ISSUE THREAD

**Issue by benhudson85** [cat-cfs/cbm3_python#8]
Please add DefaultDisturbanceTypeID 0, "Annual Processes" to tblDisturbanceType in the SQLite results databases to support NIR rollup procedures and reporting queries.

**Comment by smorken** [comment]
fixed [here](https://github.com/cat-cfs/cbm3_python/commit/454cb3dd9afb25dc25a538136b2d8ef5e20bc0c9)
